parameters:
#    terminal_admin.example.class: Terminal\AdminBundle\Example

services:
#    terminal_admin.example:
#        class: %terminal_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
