<?php

namespace Terminal\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalidadRepository extends EntityRepository
{
    public function findLocalidadesByProvinciaId($provincia_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT l FROM TerminalAdminBundle:Localidad l WHERE l.provincia = :id ORDER BY l.nombre ASC'
            )->setParameter('id', $provincia_id)->getResult();
    }
    
    public function findLocalidadesByPaisId($pais_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM TerminalAdminBundle:Localidad p JOIN p.provincia pr WHERE pr.pais = :id ORDER BY p.nombre ASC'
            )->setParameter('id', $pais_id)->getResult();
    }
}
