servicios_actuales_admin:
    pattern:  /servicios_actuales_admin
    defaults: { _controller: "TerminalAdminBundle:Servicio:serviciosActualesAdmin" }
    
servicios_actualizados_admin:
    pattern:  /servicios_actualizados_admin
    defaults: { _controller: "TerminalAdminBundle:Servicio:serviciosActualizadosAdmin" }
    
servicios_actualizados:
    pattern:  /servicios_actualizados
    defaults: { _controller: "TerminalAdminBundle:Servicio:serviciosActualizados" }
    
actualizar_servicio:
    pattern:  /actualizar_servicio
    defaults: { _controller: "TerminalAdminBundle:Servicio:actualizar" }

servicio:
    pattern:  /
    defaults: { _controller: "TerminalAdminBundle:Servicio:index" }

servicio_show:
    pattern:  /{id}/show
    defaults: { _controller: "TerminalAdminBundle:Servicio:show" }

servicio_new:
    pattern:  /new
    defaults: { _controller: "TerminalAdminBundle:Servicio:new" }

servicio_create:
    pattern:  /create
    defaults: { _controller: "TerminalAdminBundle:Servicio:create" }
    requirements: { _method: post }

servicio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TerminalAdminBundle:Servicio:edit" }

servicio_update:
    pattern:  /{id}/update
    defaults: { _controller: "TerminalAdminBundle:Servicio:update" }
    requirements: { _method: post|put }

servicio_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TerminalAdminBundle:Servicio:delete" }
    requirements: { _method: post|delete }
