parameters:
#    terminal_front.example.class: Terminal\FrontBundle\Example

services:
#    terminal_front.example:
#        class: %terminal_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
